import * as THREE from 'three';
import { PALETTE } from '../config.js';
import { createVilla } from './villa.js';
import { makeGranite, makeSignText } from '../utils/textures.js';
function mat(c){ return new THREE.MeshStandardMaterial({color:c,roughness:.82}); }
function box(w,h,d,x,y,z,m){ const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m); mesh.position.set(x,y,z); mesh.castShadow=mesh.receiveShadow=true; return mesh; }
function battlements(group,w,d,y,material){ for(let x=-w/2;x<=w/2;x+=1.3){ group.add(box(.8,.6,.5,x,y,d/2+.1,material),box(.8,.6,.5,x,y,-d/2-.1,material)); } for(let z=-d/2;z<=d/2;z+=1.3){ group.add(box(.5,.6,.8,w/2+.1,y,z,material),box(.5,.6,.8,-w/2-.1,y,z,material)); } }
function pointedWindow(x,y,z,group){ const glass=mat('#8fb6c8'); glass.emissive=new THREE.Color('#82c6ff'); glass.emissiveIntensity=.15; const geo=new THREE.Shape(); geo.moveTo(-.45,-.55); geo.lineTo(-.45,.1); geo.quadraticCurveTo(0,.78,.45,.1); geo.lineTo(.45,-.55); geo.closePath(); const m=new THREE.Mesh(new THREE.ShapeGeometry(geo),glass); m.position.set(x,y,z); group.add(m); }
export function createLandmarks(ctx){ const group=new THREE.Group(); const granite=new THREE.MeshStandardMaterial({color:PALETTE.granite,map:makeGranite(1024),roughness:.86});
  const huashi=new THREE.Group(); huashi.position.set(60,ctx.getGroundHeight(60,100),100); huashi.rotation.y=-.25; huashi.add(box(12,10.2,10,0,5.1,0,granite)); const rt=new THREE.Mesh(new THREE.CylinderGeometry(3,3.2,13.8,24),granite); rt.position.set(3,6.9,5.2); rt.castShadow=rt.receiveShadow=true; huashi.add(rt); const oct=new THREE.Mesh(new THREE.CylinderGeometry(2.4,2.8,11.8,8),granite); oct.position.set(-6,5.9,-2.8); huashi.add(oct); battlements(huashi,13,11,10.8,granite); for(let i=0;i<18;i++){ const a=i/18*Math.PI*2; huashi.add(box(.7,.6,.35,3+Math.cos(a)*3,14.1,5.2+Math.sin(a)*3,granite)); } for(let x of [-3,0,3]) pointedWindow(x,5.4,-5.05,huashi); const platform=box(26,.55,20,0,-.25,0,new THREE.MeshStandardMaterial({color:'#bfb8ad',roughness:.8})); huashi.add(platform); for(let x=-13;x<=13;x+=2) huashi.add(box(.18,1.0,.18,x,.55,10.2,mat('#f5f2ea'))); huashi.add(box(5,.25,9,0,-1.2,-14,granite)); huashi.add(box(1.4,1.2,1.4,-4,.6,-8,granite),box(1.4,1.2,1.4,4,.6,-8,granite)); group.add(huashi); ctx.colliders?.addAabb(60,100,22,18,'huashi');
  const princess=createVilla({pos:[4,-42],rotY:-Math.PI/2,floors:2,w:10,d:8,roof:'gable',roofColorIdx:1,wallColorIdx:0,tower:{corner:1,round:false},porch:true,balcony:false,chimneys:1,graniteBase:true},ctx,{wallColor:PALETTE.princessGreen}); princess.name='PrincessBuilding'; group.add(princess);
  const butterfly=createVilla({pos:[-32,48],rotY:Math.PI,floors:2,w:14,d:8,roof:'hip',roofColorIdx:2,wallColorIdx:2,tower:null,porch:true,balcony:true,chimneys:1,graniteBase:true},ctx); butterfly.name='ButterflyBuilding'; group.add(butterfly);
  const marshal=createVilla({pos:[-12,48],rotY:Math.PI,floors:2,w:12,d:9,roof:'gable',roofColorIdx:0,wallColorIdx:1,tower:null,porch:true,balcony:false,chimneys:1,graniteBase:true},ctx); marshal.name='MarshalBuilding'; group.add(marshal);
  for(const [name,x,z] of [['蝴蝶楼',-32,39],['元帅楼',-12,39]]){ const sign=new THREE.Mesh(new THREE.PlaneGeometry(3,1.2),new THREE.MeshBasicMaterial({map:makeSignText(name),side:THREE.DoubleSide})); sign.position.set(x,ctx.getGroundHeight(x,z)+1.2,z); sign.rotation.y=Math.PI; group.add(sign); }
  ctx.scene.add(group); return {group}; }
