import * as THREE from 'three';
import { ROADS, PALETTE } from '../config.js';
import { makeGlowSprite, makeSignText } from '../utils/textures.js';
function pointsAlong(points, interval){ const out=[]; for(let i=0;i<points.length-1;i++){ const [x0,z0]=points[i],[x1,z1]=points[i+1]; const dx=x1-x0,dz=z1-z0,len=Math.hypot(dx,dz); for(let d=10;d<len;d+=interval){ const t=d/len; out.push([x0+dx*t,z0+dz*t,Math.atan2(dx,dz)]); } } return out; }
function box(w,h,d,c){ return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color:c,roughness:.8})); }
export function createProps(ctx){ const group=new THREE.Group(); const lampMat=new THREE.MeshStandardMaterial({color:'#183a2b',roughness:.75}); const bulbMat=new THREE.MeshStandardMaterial({color:PALETTE.lampGlow,emissive:PALETTE.lampGlow,emissiveIntensity:1.4}); const glowTex=makeGlowSprite(); const lamps=[];
  for(const r of ROADS){ for(const [x,z,a] of pointsAlong(r.points,25)){ const side=((lamps.length%2)*2-1); const off=r.width/2+2.4; const px=x+Math.cos(a)*off*side, pz=z-Math.sin(a)*off*side; const y=ctx.getGroundHeight(px,pz); const pole=new THREE.Group(); const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.08,.12,3.2,8),lampMat); shaft.position.y=1.6; pole.add(shaft); const arm=box(1.0,.08,.08,'#183a2b'); arm.position.set(.42,3.15,0); pole.add(arm); const bulb=new THREE.Mesh(new THREE.SphereGeometry(.22,10,8),bulbMat); bulb.position.set(.95,3.08,0); pole.add(bulb); const glow=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,opacity:.55})); glow.scale.set(3.4,3.4,1); glow.position.set(.95,3.08,0); pole.add(glow); pole.position.set(px,y,pz); group.add(pole); lamps.push({pole,glow,bulb}); ctx.colliders?.addCircle(px,pz,.25,'lamp'); } }
  const intersections=[[-120,-75,'韶关路 / 武胜关路'],[-60,-75,'宁武关路 / 武胜关路'],[0,-75,'居庸关路 / 武胜关路'],[60,-75,'紫荆关路 / 武胜关路'],[115,-75,'嘉峪关路 / 武胜关路'],[-120,-10,'韶关路 / 正阳关路'],[-60,-10,'宁武关路 / 正阳关路'],[0,-10,'居庸关路 / 正阳关路'],[60,-10,'紫荆关路 / 正阳关路'],[115,-10,'嘉峪关路 / 正阳关路'],[-120,55,'韶关路 / 山海关路'],[-60,55,'宁武关路 / 山海关路'],[0,55,'居庸关路 / 山海关路'],[60,55,'紫荆关路 / 山海关路']]; intersections.forEach(([x,z,label],i)=>{ const road={name:label}; const post=new THREE.Group(); const stone=box(.55,1.1,.55,PALETTE.granite); stone.position.y=.55; post.add(stone); const sign=new THREE.Mesh(new THREE.PlaneGeometry(2.8,1.4),new THREE.MeshBasicMaterial({map:makeSignText(road.name),side:THREE.DoubleSide})); sign.position.y=1.5; sign.rotation.y=i%2?Math.PI/2:0; post.add(sign); post.position.set(x+3,ctx.getGroundHeight(x,z),z+3); group.add(post); ctx.colliders?.addCircle(x+3,z+3,.35,'sign'); });
  for(let i=0;i<6;i++){ const bench=box(3,.25,.7,'#6a3f2a'); bench.position.set(-50+i*20,ctx.getGroundHeight(-50+i*20,82)+.5,82); group.add(bench); }
  for(let i=0;i<4;i++){ const hx = i * 16 - 130; const hz = 94; const hut=box(4,2.5,3,['#2e7d8c','#c8502e','#f2c14e','#3f6151'][i]); hut.position.set(hx, ctx.getGroundHeight(hx,hz)+1.25, hz); group.add(hut); ctx.colliders?.addAabb(hx,hz,4,3,'hut'); }
  const railMat=new THREE.MeshStandardMaterial({color:'#f5f2ea',roughness:.65}); for(let x=-40;x<82;x+=3){ const p=new THREE.Mesh(new THREE.CylinderGeometry(.07,.1,1.1,8),railMat); p.position.set(x,ctx.getGroundHeight(x,78)+.55,78); group.add(p); }
  const pointLights=[new THREE.PointLight(PALETTE.lampGlow,6,12),new THREE.PointLight(PALETTE.lampGlow,6,12)]; pointLights.forEach(l=>group.add(l)); ctx.lamps=lamps; ctx.scene.add(group); return {group, update(dt,t){ const pp=ctx.player?.position; if(pp){ lamps.slice().sort((a,b)=>a.pole.position.distanceToSquared(pp)-b.pole.position.distanceToSquared(pp)).slice(0,2).forEach((l,i)=>pointLights[i].position.copy(l.pole.position).add(new THREE.Vector3(.95,3.08,0))); } const fog=ctx.currentPreset==='fog'; lamps.forEach(l=>l.glow.scale.setScalar(fog?7.5:3.4)); }}; }
