import * as THREE from 'three';
import { createRng } from './rng.js';

function makeCanvas(size) { const canvas = document.createElement('canvas'); canvas.width = canvas.height = size; return [canvas, canvas.getContext('2d')]; }
function tex(canvas, color = true) { const t = new THREE.CanvasTexture(canvas); t.wrapS = t.wrapT = THREE.RepeatWrapping; if (color) t.colorSpace = THREE.SRGBColorSpace; t.needsUpdate = true; return t; }
export function valueNoise(x, y, seed = 1) {
  const xi = Math.floor(x), yi = Math.floor(y);
  const xf = x - xi, yf = y - yi;
  const fade = n => n * n * (3 - 2 * n);
  const hash = (i, j) => { let h = (i * 374761393 + j * 668265263 + seed * 1442695041) >>> 0; h = (h ^ (h >>> 13)) >>> 0; return ((h * 1274126177) >>> 0) / 4294967295; };
  const a = hash(xi, yi), b = hash(xi + 1, yi), c = hash(xi, yi + 1), d = hash(xi + 1, yi + 1);
  const u = fade(xf), v = fade(yf);
  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v;
}
export function fbm(x, y, seed = 1, octaves = 5) { let v = 0, amp = .5, f = 1; for (let i=0;i<octaves;i++){ v += amp * valueNoise(x*f,y*f,seed+i*17); f*=2; amp*=.5; } return v; }
function fillNoise(size, base, accent, seed, scale = 18) { const [c, g] = makeCanvas(size); const img = g.createImageData(size,size); const b = new THREE.Color(base), a = new THREE.Color(accent); for(let y=0;y<size;y++) for(let x=0;x<size;x++){ const n=fbm(x/scale,y/scale,seed,5); const col=b.clone().lerp(a,n); const i=(y*size+x)*4; img.data[i]=col.r*255; img.data[i+1]=col.g*255; img.data[i+2]=col.b*255; img.data[i+3]=255; } g.putImageData(img,0,0); return [c,g]; }
export function makeStucco(size=512, seed=11){ const [c,g]=fillNoise(size,'#dfc9b4','#f0e6cc',seed,12); g.globalAlpha=.22; for(let i=0;i<900;i++){const v=120+Math.floor(valueNoise(i,seed)*80); g.fillStyle=`rgb(${v},${v},${v})`; g.fillRect((i*37)%size,(i*91)%size,1,1);} return tex(c); }
export function makeRoofTiles(size=512){ const [c,g]=makeCanvas(size); g.fillStyle='#9f3b29'; g.fillRect(0,0,size,size); for(let y=0;y<size;y+=28){ g.fillStyle=y%56?'#b5502f':'#8f3024'; g.fillRect(0,y,size,4); for(let x=(y%56?20:0);x<size;x+=48){ g.strokeStyle='rgba(40,10,6,.28)'; g.beginPath(); g.moveTo(x,y); g.lineTo(x+10,y+28); g.stroke(); }} return tex(c); }
export function makeGranite(size=512, seed=31){ const [c,g]=fillNoise(size,'#8d877f','#b0aaa2',seed,20); g.strokeStyle='rgba(45,42,40,.55)'; g.lineWidth=2; for(let y=0;y<size;y+=48){ g.beginPath(); for(let x=0;x<size;x+=16){ g.lineTo(x,y+valueNoise(x*.05,y*.05,seed)*14); } g.stroke(); } for(let x=0;x<size;x+=64){ g.beginPath(); for(let y=0;y<size;y+=16){ g.lineTo(x+valueNoise(x*.07,y*.05,seed+7)*18,y); } g.stroke(); } return tex(c); }
export function makeAsphalt(size=512){ const [c,g]=fillNoise(size,'#4f4c46','#69645b',41,8); g.globalAlpha=.12; g.fillStyle='#111'; for(let i=0;i<700;i++) g.fillRect((i*53)%size,(i*17)%size,2,1); return tex(c); }
export function makeSand(size=512){ const [c,g]=fillNoise(size,'#d9c49a','#bca578',51,14); g.strokeStyle='rgba(255,255,255,.18)'; for(let y=20;y<size;y+=42){ g.beginPath(); for(let x=0;x<size;x+=12) g.lineTo(x,y+Math.sin(x*.05+y)*4); g.stroke(); } return tex(c); }
export function makeGrass(size=512){ return tex(fillNoise(size,'#3f6333','#58773d',61,18)[0]); }
export function makePlaneBark(size=512){ const [c,g]=fillNoise(size,'#9b8c70','#d8d0ba',71,9); for(let i=0;i<80;i++){ g.fillStyle=i%2?'rgba(80,70,55,.35)':'rgba(230,225,200,.45)'; g.beginPath(); g.ellipse((i*41)%size,(i*83)%size,18,40,(i%7),0,Math.PI*2); g.fill(); } return tex(c); }
export function makeWaterNormalTexture(size=512, seed=81){ const [c,g]=makeCanvas(size); const img=g.createImageData(size,size); for(let y=0;y<size;y++) for(let x=0;x<size;x++){ const hL=fbm((x-1)/28,y/28,seed), hR=fbm((x+1)/28,y/28,seed), hD=fbm(x/28,(y-1)/28,seed), hU=fbm(x/28,(y+1)/28,seed); const nx=(hL-hR)*2, ny=(hD-hU)*2, nz=1; const len=Math.hypot(nx,ny,nz); const i=(y*size+x)*4; img.data[i]=(nx/len*.5+.5)*255; img.data[i+1]=(ny/len*.5+.5)*255; img.data[i+2]=(nz/len*.5+.5)*255; img.data[i+3]=255; } g.putImageData(img,0,0); return tex(c,false); }
export function makeLeafAlpha(shape='ginkgo', size=128){ const [c,g]=makeCanvas(size); g.clearRect(0,0,size,size); g.fillStyle='#fff'; g.translate(size/2,size/2); if(shape==='maple'){ g.beginPath(); for(let i=0;i<10;i++){ const r=i%2?24:54; const a=-Math.PI/2+i*Math.PI/5; g.lineTo(Math.cos(a)*r,Math.sin(a)*r); } g.closePath(); g.fill(); } else { g.beginPath(); g.moveTo(0,42); g.arc(0,12,50,Math.PI*.95,Math.PI*2.05); g.closePath(); g.fill(); } return tex(c,false); }
export function makeGlowSprite(size=256){ const [c,g]=makeCanvas(size); const grd=g.createRadialGradient(size/2,size/2,0,size/2,size/2,size/2); grd.addColorStop(0,'rgba(255,199,115,.85)'); grd.addColorStop(.35,'rgba(255,199,115,.24)'); grd.addColorStop(1,'rgba(255,199,115,0)'); g.fillStyle=grd; g.fillRect(0,0,size,size); return tex(c); }
export function makeCloud(size=512, seed=91){ const [c,g]=makeCanvas(size); g.clearRect(0,0,size,size); for(let i=0;i<18;i++){ const r=50+valueNoise(i,seed)*90; const x=size*(.12+valueNoise(i,seed+3)*.76); const y=size*(.32+valueNoise(i,seed+6)*.34); const grd=g.createRadialGradient(x,y,0,x,y,r); grd.addColorStop(0,'rgba(255,255,255,.75)'); grd.addColorStop(1,'rgba(255,255,255,0)'); g.fillStyle=grd; g.fillRect(0,0,size,size); } return tex(c); }
export function makeSignText(text, size=256){ const [c,g]=makeCanvas(size); g.fillStyle='#f5f2ea'; g.fillRect(0,0,size,size/2); g.strokeStyle='#b63222'; g.lineWidth=10; g.strokeRect(6,6,size-12,size/2-12); g.fillStyle='#9b241c'; g.font='bold 34px sans-serif'; g.textAlign='center'; g.textBaseline='middle'; g.fillText(text, size/2, size/4); return tex(c); }
export function makeFoamStrip(size=512, seed=101){ const [c,g]=makeCanvas(size); const img=g.createImageData(size,size); for(let y=0;y<size;y++) for(let x=0;x<size;x++){ const band=Math.exp(-Math.pow((y-size*.5)/(size*.16),2)); const n=fbm(x/24,y/9,seed,4); const a=Math.max(0,band*(n-.25))*210; const i=(y*size+x)*4; img.data[i]=255; img.data[i+1]=255; img.data[i+2]=255; img.data[i+3]=a; } g.putImageData(img,0,0); return tex(c); }
export function makeAllTexturePreview(seed='preview'){ const rng=createRng(seed); return { stucco:makeStucco(256,rng.int(1,999)), roof:makeRoofTiles(256), granite:makeGranite(256), asphalt:makeAsphalt(256), sand:makeSand(256), grass:makeGrass(256), bark:makePlaneBark(256), waterNormal:makeWaterNormalTexture(256), ginkgo:makeLeafAlpha('ginkgo'), maple:makeLeafAlpha('maple'), glow:makeGlowSprite(256), cloud:makeCloud(256), sign:makeSignText('居庸关路'), foam:makeFoamStrip(256) }; }
